# Generated by Django 4.0.6 on 2022-07-30 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='detail',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
