# Generated by Django 4.0.6 on 2022-07-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_tasklist_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='detail',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
