# Generated by Django 4.0.6 on 2022-07-31 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_tasklist_detail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasklist',
            options={'ordering': ['-created_at']},
        ),
    ]
