# Generated by Django 4.0.6 on 2022-07-31 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_tasklist_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
