# Generated by Django 4.0.6 on 2022-08-01 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_remove_tasklist_author_tasklist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='user',
        ),
    ]
